baseurl = "http://garfieldnate.github.io/"
languageCode = "en-US"
title = "Garfield Nate"
theme = "hugo-multi-bootswatch"

pygmentsCodefences = true
pygmentsStyle = "colorful"
pygmentsOptions = "linenos=true"

[permalinks]
    # Same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"

[author]
    # Optional. Used in RSS feed meta information.
    name = "Nathan Glenn"
    email = "garfieldnate <at> gmail <dot> com"

[params]
    # language code for your website
    languagecode = "en-US"

    # name of the site author; used in header meta information
    author = "Nathan Glenn"

    # copyright text; used in footer
    copyright = "2011-2018 ~ Nathan Glenn"

    # social links, used in footer, these must be full URLs.
    github      = "https://github.com/garfieldnate"
    goodreads      = "https://www.goodreads.com/user/show/2794644-nathan-glenn"

    # show default summaries on the frontpage or not
    use_summaries = false

# naming of the elements in your blog/site
[params.strings]
    # name of the link to the homepage
    home_navbar_link = "Home"

    # name of the link to the blog page
    blog_navbar_link = "Archive"

    # name of the header used in the post list page
    posts_list_header = "Blog Archive"

    # used date format
    date_format = 'January 2, 2006'

[params.theme]
    inverse = false     # indicating if the theme should use inversed colors
    name = "superhero"   # name of the theme to use

    # list of possible theme names that can be used
    # name = "cerulean"
    # name = "cosmo"
    # name = "cyborg"
    # name = "default"
    # name = "flatly"
    # name = "journal"
    # name = "lumen"
    # name = "paper"
    # name = "readable"
    # name = "sandstone"
    # name = "simplex"
    # name = "slate"
    # name = "spacelabs"
    # name = "superhero"
    # name = "united"
    # name = "yeti"
